### PR TITLE
Implement parameter handling services

### PR DESCRIPTION
**Pull request by m-dahl**
This PR should add functionality to dynamically update parameters of a node.

- [x] Setting parameters (rcl_interfaces/srv/SetParameters)
- [ ] Setting parameters atomically (rcl_interfaces/srv/SetParametersAtomically) 
- [ ] Describe paramters (rcl_interfaces/srv/DescribeParameters)
- [ ] Get parameter types (rcl_interfaces/srv/GetParameterTypes)
- [x] Get parameters (rcl_interfaces/srv/GetParameters)
- [ ] List available parameters (rcl_interfaces/srv/ListParameters)

I guess r2r needs to be extended with descriptions and bounds in order to be able to implement this api.

Also unsure what the usecase for having atomic and non-atomic updates is. Why not always atomic?

Additionally, I see that the other APIs allow for setting callbacks that are called when specific parameters are updated. We should probably have something similar.

### CODE REVIEW

**Comment by m-dahl** [comment]
The first commit implements SetParameters and updates the parameters example.

**Comment by mschuckmann** [comment]
Hi thank you for getting this started I'm starting to work on expanding this to implement the remaining tasks, however my first tasks is going to be working out how to refactor what you have started to work with the new services as streams architecture. I'm still new enough to Rust that I don't quite see how to do it, any recommendations?

**Comment by m-dahl** [comment]
Hi,

Sorry for the late reply. I have been refactoring the code a bit and in the coming days I intend to revive this branch on top of master, including a working example which you could build upon.

**Comment by mschuckmann** [comment]
Great thanks I look forward to seeing what you have. 
For the time being I've implemented most of the parameter services in my own application and learned a lot so hopefully I can take that knowledge and apply to this crate in the near future.

**Comment by m-dahl** [comment]
Hi,

I have updated this PR to master, added handling of the "get parameters" service as well as a rudimentary "parameter changed" event stream. This functionality is enough for my personal use-cases so I will just merge this pr as it is to get it into master. If you want to improve it feel free to open a new PR!

**Pull request merged**
