### PR TITLE
Add Quality of Service

### PR DESCRIPTION
**Pull request by midnightexigent**
fixes: #23 

Since this is still pre-1.0, API breakage is okay right ? If yes, I could update the examples 

However, if not, how would you like to do it ? A quick and dirty way would be to add functions/methods suffixed with `*_with_qos`.  The better solution IMO would be to overhaul the API for it to use some sort of builder pattern but that would require a significant effort  

Also, I took the liberty to run `cargo fmt` and to fix some of `cargo clippy`'s warnings

### CODE REVIEW

**Comment by midnightexigent** [comment]
I just updated the examples, tests, upgraded the dependencies, rust edition to 2021 and made `cargo clippy` happy on a separate [branch](https://github.com/midnightexigent/r2r/tree/rust-2021)  

Let me know which one you'd like to merge

**Comment by m-dahl** [comment]
Hi,

this is great, thanks for taking the time! 

> Since this is still pre-1.0, API breakage is okay right ? If yes, I could update the examples
> However, if not, how would you like to do it ? A quick and dirty way would be to add functions/methods suffixed with `*_with_qos`. The better solution IMO would be to overhaul the API for it to use some sort of builder pattern but that would require a significant effort

Lets break the API for now and think about overhauling the API for later.

> Also, I took the liberty to run `cargo fmt` and to fix some of `cargo clippy`'s warnings
> I just updated the examples, tests, upgraded the dependencies, rust edition to 2021 and made `cargo clippy` happy on a separate [branch](https://github.com/midnightexigent/r2r/tree/rust-2021)
> 
> Let me know if you prefer that one for this PR

Since you did the work already I think we could just include it here to get it in master.

Since you credit the rclrust, which has an apache license, repo in qos.rs I guess we need to make the licence for that file clear and maybe add some note in the readme about that before making a new release.

**Comment by m-dahl** [comment]
Me neither but I will try 😄 . I will add the license stuff and make a new release later this week. Thanks for your contributions.

**Comment by m-dahl** [comment]
Released this as 0.6.0. I hope it works!

**Comment by midnightexigent** [comment]
Great !

**Pull request merged**
