### PR TITLE
feat: use quote to generate code

### PR DESCRIPTION
**Pull request by JiangengDong**
Rewrite the codegen with `quote!`, so it will be easier to add new features like [the static array](https://github.com/sequenceplanner/r2r/issues/48). 

Progress: 
- [x] rewrite `r2r_msg_gen`
- [x] `cargo check` passes
- [x] `cargo test` passes 
- [ ] rewrite `r2r`'s build script to also use `quote`

Other thoughts
- [ ] redesign crate dependency so `r2r_msg_gen` is used as a build-dependency of `r2r` only. After this PR, `proc-macro2` and `quote` are runtime dependencies of `r2r`, which is not a good idea. 
- [ ] use `syn` to parse `rust-bindgen`'s output, instead of accessing `rosidl_typesupport_introspection_c__MessageMembers`

### CODE REVIEW

**Comment by m-dahl** [comment]
Looks like a good start! I think the errors you get on galactic are related to the ros constants either being renamed or maybe moved between the ros versions. I vaguely remember hacking around it, I can take a closer look when I find some time.

**Comment by m-dahl** [comment]
I looked at the issue with the constants and I see I had already written a comment about it in the code which I'm sure you saw. I think the cleanest way to handle it is to do conditional compilation on the ROS_DISTRO environment variable, and just have different cases for humble and foxy, galactic (I think these should behave the same). Then we don't need to duplicate the constants.

> redesign crate dependency so r2r_msg_gen is used as a build-dependency of r2r only. After this PR, proc-macro2 and quote are runtime dependencies of r2r, which is not a good idea.

Yes that sounds like a good idea. We could do that later as a separate pr.

> use syn to parse rust-bindgen's output, instead of accessing rosidl_typesupport_introspection_c__MessageMembers

My initial feeling is that this will be more trouble than its worth, but feel free to take a stab at it, it could be fun 😄

**Comment by m-dahl** [comment]
Hi, I pushed some code that sets configuration options depending on the ROS_DISTRO. If you rebase on top of ccdfc1e you can use `#[cfg(r2r__ros__distro__galactic)]` etc to trigger conditional compilation.

**Comment by JiangengDong** [comment]
Pushed a fix. I tested this under foxy, galactic and humble, and all tests passed.

**Comment by m-dahl** [comment]
Hi! I tried your branch now but I noticed some issues because I have the `test_msgs` package (`ros-humble-test-msgs` if you are on ubuntu), which are good to have sourced when working on this. I will update the CI to include those for more comprehensive testing. 

Also now I think we can just do conditional compilation in `FieldType::new` and use the different ROS enums there, then we don't need to hard code the constants and we don't need the code that check if they have changed.

**Comment by m-dahl** [comment]
Just a heads up that I force pushed some changes to your branch. I fixed the issues with test_msgs and had to add a temporary hack around the type name for static arrays for constants. But I figure we deal with that once we rework that parsing.

**Comment by jerry73204** [comment]
Hi @JiangengDong, I've done a parallel work on #58 and you may take a look.

**Comment by JiangengDong** [comment]
Hi @m-dahl sorry for my slow progress, and thank you for fixing it. I just rebased the branch to resolve the conflict with master. 

@jerry73204 I think your PR has more features than mine. One suggestion about the codegen part is that the snippet for checking the array size appears repeatedly in `fields`, `from_native`, and `copy_to_native` blocks. You can feel free to copy those from my PR. 

@m-dahl @jerry73204 what's your idea about these two PRs? I don't mind closing mine because the other one looks more feature-complete.

**Comment by m-dahl** [comment]
@JiangengDong @jerry73204 Thank you both for the improvements. It's unfortunate that there was duplicate work but that is just how it is. I am travelling at the moment and do not have much time to look at the PRs in detail the coming week. But as you say @JiangengDong it looks like @jerry73204's PR includes both using syn for parsing and also using quote in the build.rs files. But you hade some other nice cleanups included in this PR that I think we want. My suggestion would be to merge @jerry73204's pr to master as it is, and then we can open new PRs that adds some of @JiangengDong's more general code cleanups.

**Comment by JiangengDong** [comment]
This sounds good to me. I am going to close this PR and open a new one after https://github.com/sequenceplanner/r2r/pull/58 is merged. 

@jerry73204 let me know if you need any help on your PR.

**Comment by m-dahl** [comment]
Cool @JiangengDong . I just merged #58.

**Pull request closed without merging**
