### PR TITLE
Tidy code: Proper Cargo workspace, run rustfmt and fix clippy warnings

### PR DESCRIPTION
**Pull request by jerry73204**
This PR introduces quality improvement changes. The following works have been done:

- Make a proper Cargo workspace. The `r2r` crate is moved into the `repo/r2r/` directory. The topmost `Cargo.toml` specifies the member crates.
- Apply `rustfmt` changes.
- Fix clippy warnings.
- Add \*\~, .\*\~ and #*# to `.gitignore`

### CODE REVIEW

**Comment by jerry73204** [comment]
The CI failed because r2r requires a minimum Rust version 1.61 to compile due to the usage of `Vec::retain_mut`. However, the CI docker ships with Rust 1.57 which is too old.

**Comment by jerry73204** [comment]
@kristoferB Do you consider updating CI or using 3rd party crate to workaround with retain_mut?

**Comment by kristoferB** [comment]
It is on my todo list to update the docker images. I will try to fix that during the holidays. @m-dahl will review the code and merge the pull request or suggest changes. But he will work on that in January since he is on parental leave now.

**Comment by jerry73204** [comment]
Understood. Thanks.

**Comment by m-dahl** [comment]
Cool, thanks for your work! I will take a look at this and your other PR next week.

**Pull request merged**
